### ISSUE TITLE
DeleteStatistic Does Not Appear To Be Working

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#238]
I'm trying to "reset" my stats by deleting them using:
https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Stats/Manager/WinRT/StatisticManager_WinRT.h#L132

    void Scenarios::Scenario_DeleteAllStats(_In_ MainPage^ ui, Microsoft::Xbox::Services::XboxLiveContext^ xboxLiveContext)
    {
        StatisticManager^ mgr = StatisticManager::SingletonInstance;
        if (mgr == nullptr) return;

        Array<String^>^ Stats = {
            L"Score",
            L"HighScore",
            L"OceanWaveHighScore",
            L"ElvenRuinsHighScore",
            :
        };

        for (String^ stat : Stats)
        {
            mgr->DeleteStatistic(xboxLiveContext->User, stat);
        }
        mgr->RequestFlushToService(xboxLiveContext->User);
    }

But after executing the above I am able to read the old stat values using Scenario_ReadStat.

**Comment by jasonsandlin** [comment]
After this code, did you quit and restart the app for it to re-read the stats from the service?

**Comment by jasonsandlin** [comment]
Please reopen this isn't working

**Comment by r2d2Proton** [comment]
I was performing this in the debugger. The delete tasked finished, I tried the read again before exiting the application.

**Comment by jasonsandlin** [comment]
Yeah, delete doesn't cause it to re-query the service or clear out the in memory copy.  We can add this to the backlog

**Comment by r2d2Proton** [comment]
Okay, thank you.

**Comment by r2d2Proton** [comment]
Jason, I rebooted my machine twice, additionally completely powered off my machine two more times, a total of four times starting fresh, and my old stats are still there.

After each reboot I deleted the stats, exited the Scenarios application, shutdown Visual Studio, and repeated the process. One would think that after four times the stats would be deleted but there not.

By any chance is there a file I can delete?

Is there a way to "reopen" this issue or do I need to recreate it?

**Comment by jasonsandlin** [comment]
There's no file.  Fiddler likely will the stats still being returned.  We'll have to look into why

**Comment by jasonsandlin** [comment]
Delete stat & get stat is working for me.  

I added delete stat to the C++/CX test app to verify:
https://github.com/Microsoft/xbox-live-api/commit/d8b1cf9e998691f3db9911bc0b29ef80aa82541b

In your version of the test app the "Get Stat" button called "Get Leaderboard" API which is confusing because they are different concepts.  Stats and leaderboards behave differently.  This is now fixed in the latest version of the test app.

Here's what I did to verify delete is working:

1) Launch C++/CX test app

2) Click "Get Stat" which in turn calls GetStatistic() for each stat that previously was written.   https://github.com/Microsoft/xbox-live-api/blob/master/Tests/CppCxTests/Social/UWP/Scenarios.cpp#L178 

3) Click "Write Stat" which writes 1002 to "HighScore" https://github.com/Microsoft/xbox-live-api/blob/master/Tests/CppCxTests/Social/UWP/Scenarios.cpp#L192

4) Click "Get Stat" again.  Now you should see 1002 in "HighScore"

5) Click "Delete Stat" which deletes "HighScore" & flushes.  https://github.com/Microsoft/xbox-live-api/blob/master/Tests/CppCxTests/Social/UWP/Scenarios.cpp#L205

6) Click "Get Stat" again.  Now you should now NOT see "HighScore" cause it was deleted -- both locally and from the service.

7) Call "Get Leaderboard" and you'll see "HighScore" still show up in the global leaderboard.  Global leaderboards currently remember the highest (or lowest, depending on config) value you set, but this may change in the future.  There's no way for a Creator to reset a leaderboard currently.  For now, Creators should use a new stat name if you need to reset the leaderboard data.
