### ISSUE TITLE
Fetching game list for specific user/profile

### ISSUE THREAD

**Issue by unckleg** [microsoft/xbox-live-api#513]
Is there REST endpoint for fetching list of games for specific XUID or authorized profile.

**Comment by unckleg** [comment]
Any info for this one ?

**Comment by aablackm** [comment]
Hi @unckleg, we're looking into your question, thank you for your patience.

**Comment by unckleg** [comment]
@aablackm Thanks, waiting for response :)

**Comment by CameronGoodwin** [comment]
@unckleg Hi I'm Cameron from the Xbox ATG team.  All of the Xbox Live Service API's are shims for REST based service calls.  So yes, there is a URL to the Xbox Inventory service that you can use to check what the user is entitled to.  But you must be providing an XSTS token in the Authorization header for that service.  Can you give me some more info on why you are wanting to call the URL directly or what the flow of your code would be?

If you are wanting to do this check from a server backend (b2b) that can be done and is outlined in many of the Xbox Live developer forum posts.  For b2b you would need a Delegated Auth XSTS token which is a whole other discussion, but there we have good samples, whitepapers, and past conference talks on them.

**Comment by unckleg** [comment]
Hi @CameronGoodwin I'll take a look tomorrow at our implementation and inform you detailed about the same. So we can discuss about  the problem.

**Comment by unckleg** [comment]
Hi @CameronGoodwin,

I didn't mention that we are authorized and we are sending XBL3.0 authorization header for every request. Many other services that are behind the Authorization layer are working correctly but we just have problem with Inventory service, when I send request to 'inventory' endpoint I get '403 forbidden' status code.

Here is linked issue: #514

**Comment by unckleg** [comment]
@CameronGoodwin @aablackm @KevinAsgari 

Any news on this one ? 

Thanks!

**Comment by CameronGoodwin** [comment]
Sorry @unckleg I apparently am not getting notifications when there are updates to this thread.  Without seeing a trace or the MS-CV value of a 403's response header to look up some logs it is not easy to say what the issue is.  However, if you have delegated auth working for other services my guess would be that you are using the same XSTS token for those services as you are for calling Xbox Inventory.  In that case then I would expect a 403 ;).  You see most of the Xbox Live services use the relying party for "http://xboxlive.com", but xbox inventory uses a different one.  That means you have to specifically ask for a delegated auth XSTS token with a relying party of "http://licensing.xboxlive.com" to be able to talk to the xbox inventory service.  Check to make sure you are asking for a token with that relying party.

**Comment by jasonsandlin** [comment]
Please follow up on the Xbox Live developer forum if you have further questions on this topic
