### ISSUE TITLE
Presence resource is not working as expected.

### ISSUE THREAD

**Issue by khalaki** [microsoft/xbox-live-api#580]
We are using RESTFul Xbox Live Services for our business logic. We have found that the Presence resource is not working as expected.
Presence changes for Xbox FIFA 22 are not updating according to the game.
The same behavior was for /users/batch, /users/me, /users/xuid({xuid}).
Instead of an actual game, the resource returns info from the previous game.
Can you assist with this issue?

Thank you  
Best regards

**Comment by jplafonta** [comment]
Could you please post your issue on the Xbox Developer forums instead.  That is monitored and someone should be able to answer your question more quickly.

Thanks!

**Comment by MaxKomarenski** [comment]
Hi @jplafonta 
I am working on the same project with @khalaki and we have tried to reach Xbox Developer forum on https://forums.xboxlive.com/ but this site is on maintenance since December. We appreciate if you provide us with link where somebody could help us. 

Thank you

![image (36)](https://user-images.githubusercontent.com/24692079/150354006-09a2162c-1e57-4c2f-b20c-bd5318be40f5.png)

**Comment by jasonsandlin** [comment]
Hmm, https://forums.xboxlive.com/ is the correct address and appears to be working.  Can you reach out on email to id@xbox.com if you are an ID@Xbox developer, or via your Microsoft account rep if if not and they will help you figure out the issue

Thanks

**Comment by MaxKomarenski** [comment]
Thank you @jasonsandlin.
We will check for our id@xbox.com.

Have a good day
